---
title: "Practical Machine Learning: Prediction Assignment"
author: "Yasser Gonzalez"
date: "September 2015"
output: html_document
---

# Introduction

Additional information is available at http://groupware.les.inf.puc-rio.br/har.

# Initialization

The following code fragment loads the required R packages and sets the random 
seed to ease the reproducibility of the results.

```{r results='hide', message=FALSE, warning=FALSE}
library("readr")
library("dplyr")
library("randomForest")
library("caret")
library("doMC")

set.seed(2100479551)
```

# Data Loading and Feature Selection

```{r warning = FALSE}
dataset_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
dataset_csv <- "pml-training.csv"
if (!file.exists(dataset_csv)) {
    download.file(dataset_url, dataset_csv, method = "curl")
}
dataset <- read_csv(dataset_csv)
```

```{r}
sensors <- c("forearm", "arm", "belt", "dumbbell")
vars <- c("roll_%s", "pitch_%s", "yaw_%s",
          "gyros_%s_x", "gyros_%s_y", "gyros_%s_z",
          "accel_%s_x", "accel_%s_y", "accel_%s_z",
          "magnet_%s_x", "magnet_%s_y", "magnet_%s_z")
features <- unlist(lapply(sensors, 
      function (sensor) lapply(vars, 
               function (var) sprintf(var, sensor))))
```

```{r}
dataset <- dataset %>%
    select(one_of(c("classe", features))) %>%
    mutate(classe = as.factor(classe))
```

```{r}
indices <- createDataPartition(dataset$classe, p = 0.8, list = FALSE)
training_data <- dataset[indices, ]
testing_data <- dataset[-indices, ]
```

# Exploratory Data Analysis

```{r}
```

# Building the Prediction Model

```{r}
model_file <- "model.rds"
if (!file.exists(model_file)) {
    registerDoMC(cores = 4)
    model <- train(classe ~ ., data = training_data,  
                   method = "rf",
                   tuneLength = 8, # number of mtry values
                   metric = "Accuracy",
                   trControl = trainControl(method = "cv", number = 10))
    saveRDS(model, model_file)
} else {
    model <- readRDS(model_file)
}
```

# Evaluating the Prediction Model

```{r}
confusionMatrix(predict(model, newdata = testing_data), 
                testing_data$classe)
```

# Submission Results

```{r}
testing_dataset_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
testing_dataset_csv <- "pml-testing.csv"
if (!file.exists(testing_dataset_csv)) {
    download.file(testing_dataset_url, testing_dataset_csv, method = "curl")
}

testing_dataset <- read_csv(testing_dataset_csv) %>%
    select(one_of(c("problem_id", features)))
```

```{r}
prediction <- predict(model, newdata = testing_dataset)
prediction
```

```{r}
for (i in seq(along = prediction)) {
    txt_file <- paste0("problem_id_", testing_dataset$problem_id[i], ".txt")
    write.table(prediction[i], file = txt_file, 
                quote = FALSE, row.names = FALSE, col.names = FALSE)
}
```
